# Netlify configuration file

# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Ensure 3D model files are correctly copied
  [[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to ensure proper MIME types for 3D models
[[headers]]
  for = "/3d/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "model/gltf-binary"
